'use client';
import { useEffect,useRef,useState,type CSSProperties } from 'react';
import {ArrowUpRight,ArrowDown,ArrowRight,Menu,X,Plus,Check,ChevronLeft,ChevronRight} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';

const league='/winterleague';
const teams=[{name:'Red',id:'red',number:'01',color:'#fc786e'},{name:'Black',id:'black',number:'02',color:'#283e37'},{name:'White',id:'white',number:'03',color:'#fff9ea'}];
const photos=[{src:'/matchday.webp',alt:'A football on a sunlit grass pitch with players in the distance',caption:'Early light.'},{src:'/pitch.jpg',alt:'Football boots and a ball on bright green grass',caption:'First touch.'}];
const questions=[
  ['How does the Winter league work?','Red, Black and White rotate through short games. Two teams play; the winner stays and the other team rotates off. Each round lasts 10 minutes or ends when one team scores two goals. After a draw, the previous winning side rotates off. The organiser sets the opening-round draw exit.'],
  ['Where do I find my profile?','Open the league and choose My profile. Sign in with your email and use the personal invitation from your organiser to connect your account. You can update your name, age, height, district, position and portrait there.'],
  ['How do I vote for Player of the Day?','Your organiser opens voting after the game and shares the link. Choose one attending player from either of the other two teams. You have one anonymous vote; your own team cannot be selected.'],
  ['When do scores and videos appear?','The organiser adds results, goals, assists, match replays and individual highlights. Voting can open right after the session while scores are entered later.']
];
function Ball({className=''}:{className?:string}){return <svg className={className} viewBox="0 0 100 100" fill="none" aria-hidden="true"><circle cx="50" cy="50" r="46" stroke="currentColor" strokeWidth="2"/><path d="M50 28 72 44 63 70H37L28 44Z" fill="currentColor"/><path d="M50 28V4M72 44l22-8M63 70l15 18M37 70 22 88M28 44 6 36M14 22l18 1M68 23l18-1M91 64l-8 17M50 96l-9-8M9 64l8 17" stroke="currentColor" strokeWidth="3"/></svg>}
function Pitch(){return <svg className="fc-pitch" viewBox="0 0 300 390" fill="none" aria-hidden="true"><rect x="21" y="20" width="258" height="350" rx="5"/><path d="M21 195h258M89 20v58h122V20M111 20v24h78V20M89 370v-58h122v58M111 370v-24h78v24"/><circle cx="150" cy="195" r="42"/><circle cx="150" cy="195" r="3" fill="currentColor"/><circle className="fc-dot dot-one" cx="102" cy="140" r="9"/><circle className="fc-dot dot-two" cx="199" cy="238" r="9"/><circle className="fc-dot dot-three" cx="150" cy="273" r="7"/></svg>}
export default function HomePage(){
  const root=useRef<HTMLDivElement>(null),[menu,setMenu]=useState(false),[motion,setMotion]=useState(true),[photo,setPhoto]=useState<number|null>(null);
  useEffect(()=>{
    const hash=new URLSearchParams(location.hash.slice(1));
    if(hash.has('invite')||hash.has('setup')){location.replace(league+location.search+location.hash);return;}
    const el=root.current;if(!el)return;
    const preference=matchMedia('(prefers-reduced-motion: reduce)');setMotion(!preference.matches);
    const update=()=>setMotion(!preference.matches);preference.addEventListener('change',update);
    const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('fc-seen');observer.unobserve(entry.target);}}),{threshold:.12});
    el.querySelectorAll('.fc-reveal').forEach(node=>observer.observe(node));
    el.classList.add('fc-ready');
    return ()=>{observer.disconnect();preference.removeEventListener('change',update);};
  },[]);
  useEffect(()=>{
    const el=root.current;if(!el||!motion)return;
    let frame=0;const scroll=()=>{if(frame)return;frame=requestAnimationFrame(()=>{el.style.setProperty('--fc-scroll',String(Math.min(window.scrollY,900)));frame=0;});};
    scroll();window.addEventListener('scroll',scroll,{passive:true});return()=>{window.removeEventListener('scroll',scroll);cancelAnimationFrame(frame);};
  },[motion]);
  return <div className={'fc-home'+(!motion?' fc-still':'')} ref={root}>
    <a href="#main" className="fc-skip">Skip to content</a>
    <header className="fc-nav"><a className="fc-brand" href="/" aria-label="Prithvi FC home"><span className="fc-monogram">P<span>FC</span></span><span>PRITHVI<span>FOOTBALL CLUB</span></span></a><nav aria-label="Main navigation" className={menu?'fc-nav-links fc-menu-open':'fc-nav-links'}><a href="#club" onClick={()=>setMenu(false)}>The club</a><a href="#teams" onClick={()=>setMenu(false)}>Our teams</a><a href="#league" onClick={()=>setMenu(false)}>Winter league</a><a href={league+'?view=profile'} className="fc-member">Player login<ArrowUpRight size={18}/></a></nav><button className="fc-menu" aria-label={menu?'Close menu':'Open menu'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
    <main id="main">
      <section className="fc-hero" aria-labelledby="hero-title"><div className="fc-hero-top"><span className="fc-small">HRSC–PRITHVI</span><a href="#league" className="fc-season"><span/>Winter league 2026–27<ArrowUpRight size={16}/></a></div><div className="fc-hero-title"><h1 id="hero-title">PRITHVI<span>FOOTBALL CLUB<span className="fc-title-star" aria-hidden="true">✳</span></span></h1><p>HRSC–Prithvi.<br/>Red, Black and White.</p></div>
        <div className="fc-hero-media"><img className="fc-parallax" src="/matchday.webp" alt={photos[0].alt} fetchPriority="high" width="1672" height="941"/><div className="fc-photo-shade"/><div className="fc-photo-label"><span>THE WINTER LEAGUE</span><p>7:00–8:30<span>AM</span></p><a className="fc-button fc-lime" href={league}>Enter the league<ArrowUpRight/></a></div><div className="fc-floating-note"><Ball/><span>Red. Black. White.<br/><b>See you on the pitch.</b></span></div><a href="#club" className="fc-down" aria-label="Scroll to the club"><ArrowDown/></a></div>
        <div className="fc-hero-foot"><span>Football, together.</span><span>SCROLL TO EXPLORE <ArrowDown size={14}/></span></div>
      </section>
      <section id="club" className="fc-club fc-section fc-reveal"><div className="fc-section-label"><span>01 / THE CLUB</span><span className="fc-sticker" aria-hidden="true">PFC ↗</span></div><div className="fc-club-copy"><h2>A club.<br/><em>Three teams.</em></h2><div><p>This is Prithvi FC. A shared space for our football, our players and the games we play together.</p><p>The Winter league brings Red, Black and White together every week. Follow the results, find your teammates and keep your profile up to date.</p><a href={league+'?view=players'} className="fc-text-link">Meet the players<ArrowUpRight/></a></div></div></section>
      <section id="league" className="fc-league fc-section fc-reveal"><div className="fc-league-copy"><span className="fc-small">02 / WINTER LEAGUE</span><h2>The Winter<br/><em>league.</em></h2><p>Three teams. Two on the pitch.<br/>Ten minutes to make it count.</p><div className="fc-rule-row"><div><b>10</b><span>minutes a round</span></div><div><b>02</b><span>goals to finish</span></div></div><a className="fc-button fc-dark" href={league}>Open Winter league<ArrowUpRight/></a></div><div className="fc-league-art"><div className="fc-art-orbit"/><Pitch/><span className="fc-art-tag">WINNER STAYS ↗</span><Ball className="fc-art-ball"/><span className="fc-art-caption">RED / BLACK / WHITE</span></div><div className="fc-league-links"><a href={league+'?view=matchdays'}><span>Match days<small>Results & replays</small></span><ArrowUpRight/></a><a href={league+'?view=standings'}><span>Standings<small>Team wins & form</small></span><ArrowUpRight/></a><a href={league+'?view=vote'}><span>Player of the Day<small>Your vote, after the game</small></span><ArrowUpRight/></a></div></section>
      <section id="teams" className="fc-section fc-teams"><div className="fc-section-heading fc-reveal"><div><span className="fc-small">03 / THE SQUADS</span><h2>Pick your <em>colour.</em></h2></div><a href={league+'?view=players'} className="fc-text-link">All players<ArrowUpRight/></a></div><div className="fc-team-grid">{teams.map((team,index)=><a href={league+'?view=players&team='+team.id} className={'fc-team fc-team-'+team.id+' fc-reveal'} style={{'--fc-team':team.color,'--fc-delay':index*90+'ms'} as CSSProperties} key={team.id}><div className="fc-team-top"><span>TEAM {team.number}</span><ArrowUpRight/></div><div className="fc-kit" aria-hidden="true"><svg viewBox="0 0 200 210"><path d="M65 24 33 39 8 84 44 104 54 82v111h92V82l10 22 36-20-25-45-32-15c-7 23-63 23-70 0Z"/><path className="fc-kit-neck" d="M65 24c10 18 60 18 70 0"/><text x="100" y="130" textAnchor="middle">PFC</text></svg><span className="fc-kit-shadow"/></div><div className="fc-team-bottom"><h3>{team.name}</h3><span>View squad<ArrowRight size={17}/></span></div></a>)}</div></section>
      <section className="fc-section fc-moments"><div className="fc-section-heading fc-reveal"><div><span className="fc-small">04 / AROUND THE GAME</span><h2>A little <em>pitch time.</em></h2></div><Ball className="fc-section-ball"/></div><div className="fc-photo-grid">{photos.map((p,index)=><button className={'fc-moment fc-reveal moment-'+index} onClick={()=>setPhoto(index)} key={p.src} aria-label={'View photograph: '+p.caption}><img src={p.src} alt={p.alt} loading="lazy" width={index?2000:1672} height={index?1169:941}/><span><b>{p.caption}</b><Plus/></span></button>)}</div><p className="fc-photo-credit">Football photography by <a href="https://unsplash.com/@emilio_garcia" target="_blank" rel="noreferrer">Emilio Garcia</a>.</p></section>
      <section className="fc-member-section fc-section fc-reveal"><div><span className="fc-small">FOR THE PLAYERS</span><h2>Your player<br/><em>profile.</em></h2><p>Make your profile yours. Add a photo, update your position, and find your goals, assists and highlights in one place.</p><a className="fc-button fc-dark" href={league+'?view=profile'}>My player profile<ArrowUpRight/></a></div><div className="fc-member-graphic" aria-hidden="true"><div className="fc-profile-card"><span className="fc-profile-ball"><Ball/></span><div>PRITHVI FC<small>PLAYER PROFILE</small></div><div className="fc-profile-lines"><span>Position<Check size={15}/></span><span>District<Check size={15}/></span><span>Your photo<Check size={15}/></span></div><span className="fc-profile-bottom">Ready for the next game<ArrowUpRight/></span></div><span className="fc-member-flower">✳</span></div></section>
      <section id="questions" className="fc-section fc-questions fc-reveal"><div><span className="fc-small">GOOD TO KNOW</span><h2>Before<br/><em>kick-off.</em></h2></div><div className="fc-faqs">{questions.map(([title,answer])=><details key={title}><summary>{title}<Plus/></summary><p>{answer}</p></details>)}</div></section>
    </main>
    <footer className="fc-footer"><div className="fc-footer-top"><a className="fc-brand" href="/" aria-label="Prithvi FC home"><span className="fc-monogram">P<span>FC</span></span><span>PRITHVI<span>FOOTBALL CLUB</span></span></a><div><a href={league}>Winter league<ArrowUpRight size={17}/></a><a href={league+'?view=profile'}>Player login<ArrowUpRight size={17}/></a><a href="#questions">Club guide<ArrowUpRight size={17}/></a></div></div><div className="fc-footer-word" aria-hidden="true">PRITHVI <Ball/></div><div className="fc-footer-bottom"><span>© {new Date().getFullYear()} Prithvi FC</span><button onClick={()=>setMotion(!motion)} aria-pressed={motion}>Motion {motion?'on':'off'}<span className={motion?'fc-switch active':'fc-switch'}/></button><a href="#main">Back to top ↑</a></div></footer>
    <Dialog open={photo!==null} onOpenChange={open=>{if(!open)setPhoto(null)}}><DialogContent className="fc-lightbox"><DialogTitle>{photo!==null?photos[photo].caption:'Football photograph'}</DialogTitle><DialogDescription>Football photography by Emilio Garcia.</DialogDescription>{photo!==null&&<><img src={photos[photo].src} alt={photos[photo].alt}/><div className="fc-lightbox-controls"><button aria-label="Previous photograph" onClick={()=>setPhoto((photo+photos.length-1)%photos.length)}><ChevronLeft/></button><span>{photo+1} / {photos.length}</span><button aria-label="Next photograph" onClick={()=>setPhoto((photo+1)%photos.length)}><ChevronRight/></button></div></>}</DialogContent></Dialog>
  </div>;
}
